import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GitButton from "@/components/gitbutton"
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Link href='https://github.com/sreehhari'>
      <GitButton />
      </Link>

        {children}</body>
    </html>
  );
}
